### ISSUE TITLE
Could Not Reproduce the Results 

### ISSUE THREAD

**Issue by shambhavicodes** [olivesgatech/gradcon-anomaly#2]
I was trying to reproduce the results on CIFAR Dataset following the shared instructions. However, the results were different every time I ran the code and didn't match the ones shared in the paper.

Here's the result I got : 
1. 0.7210 0.4727 0.6329 0.5940 0.7250 0.5682 0.6899 0.5220 0.7820 0.4518 0.6160
2. 0.7595 0.5261 0.6065 0.5876 0.7026 0.5190 0.6954 0.5388 0.7505 0.5290 0.6215

**Comment by gukyeongkwon** [comment]
Hi, thanks for your interests in our paper. 

To obtain the same result for each run, you may want to define a random seed in the beginning of the code as follows. Also, the results may vary depending on the random seed.

```
parser.add_argument(
        "--seed", type=int, default=0, help="random seed for initialization"
    )

random.seed(args.seed)
np.random.seed(args.seed)
torch.manual_seed(args.seed)
```
